name: 8labs-workflow

on:
  schedule:
    # - cron: "*/5 * * * *" # every 5 minute
    - cron: "0 18 * * *" # every day at 1am WIB
  workflow_dispatch: # manual trigger support

jobs:
  paymenter-job:
    name: paymenter-job
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install

      # 👇 Pass environment variable to disable payment
      - name: Run invoice script
        run: bun index.ts
        env:
          ENABLE_PAYMENT: ${{ vars.ENABLE_PAYMENT }}
          BASE_URL: ${{ vars.BASE_URL }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
